[package]
name = "dehydrat"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
pbr = "1.0.4"
zip = "0.6.2"
